"""rename department to departments

Revision ID: e66adb9b13cf
Revises: f8e7e44bfee7
Create Date: 2024-01-08 03:36:16.301829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e66adb9b13cf"
down_revision = "f8e7e44bfee7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("departments", "department")
    # ### end Alembic commands ###
